Разметка главной страницы.
htmlacademy-htmlcss/1932829-sedona-33 pull request #2
Opened 2022-01-23 16:24 UTC by daryadarya1

2022-01-23 17:10 UTC, hen04 requested changes
Дарья, разметка в целом верная, есть несколько недочетов, они не критичные, но их нужно поправить. 
И еще проверь, пожалуйста, код валидатором (https://validator.w3.org/), там есть несколько ошибок. 
Жду исправления и можно двигаться дальше!

2022-01-23 17:10 UTC, hen04 commented on index.html
> +    <h1 class="visually-hidden"><img src-"#" class="welcome-image" alt="Welcome to Sedona"></h1>
<img src="" ... >

2022-01-23 17:10 UTC, hen04 commented on index.html
> +      <li class="item-advantages">
Здесь я бы написала название класса advantages-item

2022-01-23 17:10 UTC, hen04 commented on index.html
> +    <ol class="list-advantages">
Здесь я бы написала название класса advantages-list. Это не ошибка, пригодится такой порядок позже, когда будешь изучать БЭМ

2022-01-23 17:10 UTC, hen04 commented on index.html
> +  <section class="section-adventeges">
Здесь опечатка в названии класса advantages

2022-01-23 17:10 UTC, hen04 commented on index.html
> +      <input type="email">
У input есть еще атрибут name и placeholder. Первый нужен для отправки данных на сервер, второй -- подсказка для пользователя

2022-01-23 17:10 UTC, hen04 commented on index.html
> +  <section class="footer-messengers">
Я бы назвала не messengers, а footer-social. У нас ссылки на соцсети, а не в месссенджеры

2022-01-23 17:10 UTC, hen04 commented on index.html
> +    <a href="tel:+7 (812) 812-12-12">+7 (812) 812-12-12</a>
Здесь ошибка в атрибуте href у телефона, можно проверить валидатором https://validator.w3.org/

2022-01-23 17:10 UTC, hen04 commented on index.html
>      <p>Репозиторий создан для обучения на профессиональном онлайн‑курсе «<a href="https://htmlacademy.ru/intensive/htmlcss">HTML и CSS. Профессиональная вёрстка сайтов</a>».</p>
Эту строчку можно удалить

2022-01-23 17:19 UTC, daryadarya1 commented
Ок, спасибо!

вс, 23 янв. 2022 г., 20:10 Надя Дегтярёва ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Дарья, разметка в целом верная, есть несколько недочетов, они не
> критичные, но их нужно поправить.
> И еще проверь, пожалуйста, код валидатором (https://validator.w3.org/),
> там есть несколько ошибок.
> Жду исправления и можно двигаться дальше!
> ------------------------------
>
> In index.html
> <https://github.com/htmlacademy-htmlcss/1932829-sedona-33/pull/2#discussion_r790303468>
> :
>
> > +      <a href="#" class="logo"><img src="#" alt="Логотип сайта"></a>
> +      <nav class="main-navigation">
> +        <ul class="navigation-list">
> +          <li class="navigation-item">Главная</li>
> +          <li class="navigation-item">О Седоне</li>
> +          <li class="navigation-item">Гостиницы</li>
> +        </ul>
> +        <ul class="user-navigation">
> +          <li class="navigation-item visually-hidden">Поиск</li>
> +          <li class="navigation-item visually-hidden">Отзывы</li>
> +          <li class="navigation-item"><a href="#" class="button">Хочу сюда!</a></li>
> +        </ul>
> +      </nav>
> +    </header>
> +  <section class="welcome-title">
> +    <h1 class="visually-hidden"><img src-"#" class="welcome-image" alt="Welcome to Sedona"></h1>
>
> <img src="" ... >
> ------------------------------
>
> In index.html
> <https://github.com/htmlacademy-htmlcss/1932829-sedona-33/pull/2#discussion_r790303624>
> :
>
> > +        </ul>
> +        <ul class="user-navigation">
> +          <li class="navigation-item visually-hidden">Поиск</li>
> +          <li class="navigation-item visually-hidden">Отзывы</li>
> +          <li class="navigation-item"><a href="#" class="button">Хочу сюда!</a></li>
> +        </ul>
> +      </nav>
> +    </header>
> +  <section class="welcome-title">
> +    <h1 class="visually-hidden"><img src-"#" class="welcome-image" alt="Welcome to Sedona"></h1>
> +    <h2>Седона — небольшой городок в Аризоне, заслуживающий большего!</h2>
> +    <p>Рассмотрим 5 причин, по которым Седона круче, чем Гранд-Каньон!</p>
> +  </section>
> +  <section class="section-adventeges">
> +    <ol class="list-advantages">
> +      <li class="item-advantages">
>
> Здесь я бы написала название класса advantages-item
> ------------------------------
>
> In index.html
> <https://github.com/htmlacademy-htmlcss/1932829-sedona-33/pull/2#discussion_r790303749>
> :
>
> > +          <li class="navigation-item">Гостиницы</li>
> +        </ul>
> +        <ul class="user-navigation">
> +          <li class="navigation-item visually-hidden">Поиск</li>
> +          <li class="navigation-item visually-hidden">Отзывы</li>
> +          <li class="navigation-item"><a href="#" class="button">Хочу сюда!</a></li>
> +        </ul>
> +      </nav>
> +    </header>
> +  <section class="welcome-title">
> +    <h1 class="visually-hidden"><img src-"#" class="welcome-image" alt="Welcome to Sedona"></h1>
> +    <h2>Седона — небольшой городок в Аризоне, заслуживающий большего!</h2>
> +    <p>Рассмотрим 5 причин, по которым Седона круче, чем Гранд-Каньон!</p>
> +  </section>
> +  <section class="section-adventeges">
> +    <ol class="list-advantages">
>
> Здесь я бы написала название класса advantages-list. Это не ошибка,
> пригодится такой порядок позже, когда будешь изучать БЭМ
> ------------------------------
>
> In index.html
> <https://github.com/htmlacademy-htmlcss/1932829-sedona-33/pull/2#discussion_r790303862>
> :
>
> > +          <li class="navigation-item">О Седоне</li>
> +          <li class="navigation-item">Гостиницы</li>
> +        </ul>
> +        <ul class="user-navigation">
> +          <li class="navigation-item visually-hidden">Поиск</li>
> +          <li class="navigation-item visually-hidden">Отзывы</li>
> +          <li class="navigation-item"><a href="#" class="button">Хочу сюда!</a></li>
> +        </ul>
> +      </nav>
> +    </header>
> +  <section class="welcome-title">
> +    <h1 class="visually-hidden"><img src-"#" class="welcome-image" alt="Welcome to Sedona"></h1>
> +    <h2>Седона — небольшой городок в Аризоне, заслуживающий большего!</h2>
> +    <p>Рассмотрим 5 причин, по которым Седона круче, чем Гранд-Каньон!</p>
> +  </section>
> +  <section class="section-adventeges">
>
> Здесь опечатка в названии класса advantages
> ------------------------------
>
> In index.html
> <https://github.com/htmlacademy-htmlcss/1932829-sedona-33/pull/2#discussion_r790304104>
> :
>
> > +      </li>
> +    </ol>
> +  </section>
> +  <section class="search-hostel">
> +    <h2>Заинтересовались?</h2>
> +    <p>Укажите предполагаемые даты поездки,
> +      и мы покажем вам лучшие предложения гостиниц в Седоне
> +      </p>
> +      <a href="#">ПОИСК ГОСТИНИЦЫ В седоне</a>
> +  </section>
> +  <section class="appointment">
> +    <h2>Подпишитесь на рассылку</h2>
> +    <p>Только полезная информация и никакого спама,
> +честное бойскаутское!</p>
> +    <form class="appointment-form" action="https://echo.htmlacademy.ru/" method="post">
> +      <input type="email">
>
> У input есть еще атрибут name и placeholder. Первый нужен для отправки
> данных на сервер, второй -- подсказка для пользователя
> ------------------------------
>
> In index.html
> <https://github.com/htmlacademy-htmlcss/1932829-sedona-33/pull/2#discussion_r790304228>
> :
>
> > +    <p>Укажите предполагаемые даты поездки,
> +      и мы покажем вам лучшие предложения гостиниц в Седоне
> +      </p>
> +      <a href="#">ПОИСК ГОСТИНИЦЫ В седоне</a>
> +  </section>
> +  <section class="appointment">
> +    <h2>Подпишитесь на рассылку</h2>
> +    <p>Только полезная информация и никакого спама,
> +честное бойскаутское!</p>
> +    <form class="appointment-form" action="https://echo.htmlacademy.ru/" method="post">
> +      <input type="email">
> +      <button class="button" type="submit">Записаться</button>
> +    </form>
> +  </section>
> +<footer class="main-footer">
> +  <section class="footer-messengers">
>
> Я бы назвала не messengers, а footer-social. У нас ссылки на соцсети, а не
> в месссенджеры
> ------------------------------
>
> In index.html
> <https://github.com/htmlacademy-htmlcss/1932829-sedona-33/pull/2#discussion_r790304349>
> :
>
> > +    <h2>Подпишитесь на рассылку</h2>
> +    <p>Только полезная информация и никакого спама,
> +честное бойскаутское!</p>
> +    <form class="appointment-form" action="https://echo.htmlacademy.ru/" method="post">
> +      <input type="email">
> +      <button class="button" type="submit">Записаться</button>
> +    </form>
> +  </section>
> +<footer class="main-footer">
> +  <section class="footer-messengers">
> +    <a href="https://www.facebook.com/htmlacademy"><span class="visually-hidden">Facebook </span></a>
> +    <a href=https://twitter.com/htmlacademy_ru ><span class="visually-hidden">Twitter </span></a>
> +    <a href=https://www.youtube.com/c/HTMLAcademyRUS class="visually-hidden"><span class="visually-hidden">Youtube</span></a>
> +  </section>
> +  <section class="footer-phone">
> +    <a href="tel:+7 (812) 812-12-12">+7 (812) 812-12-12</a>
>
> Здесь ошибка в атрибуте href у телефона, можно проверить валидатором
> https://validator.w3.org/
> ------------------------------
>
> In index.html
> <https://github.com/htmlacademy-htmlcss/1932829-sedona-33/pull/2#discussion_r790304389>
> :
>
> > +      <button class="button" type="submit">Записаться</button>
> +    </form>
> +  </section>
> +<footer class="main-footer">
> +  <section class="footer-messengers">
> +    <a href="https://www.facebook.com/htmlacademy"><span class="visually-hidden">Facebook </span></a>
> +    <a href=https://twitter.com/htmlacademy_ru ><span class="visually-hidden">Twitter </span></a>
> +    <a href=https://www.youtube.com/c/HTMLAcademyRUS class="visually-hidden"><span class="visually-hidden">Youtube</span></a>
> +  </section>
> +  <section class="footer-phone">
> +    <a href="tel:+7 (812) 812-12-12">+7 (812) 812-12-12</a>
> +  </section>
> +  <s [...]

2022-01-25 16:53 UTC, hen04 requested changes
Даша, на странице index.html все хорошо, но на странице catalog.html есть несколько правок. Внеси их, пожалуйста.

2022-01-25 16:53 UTC, hen04 commented on catalog.html
> +        <section>
Нужно название класса для section

2022-01-25 16:53 UTC, hen04 commented on catalog.html
> +        <ul class="breadcrumbs-list visually-hidden">
А почему тут класс visually-hidden?  visually-hidden -- скрывает содержимое от пользователя и показывает скринридерам, а у нас не нужно здесь ничего скрывать

2022-01-25 16:53 UTC, hen04 commented on catalog.html
> +            <button class="button" type="submit">Сбросить</button>
В этом случае `type="reset"`

2022-01-25 16:53 UTC, hen04 commented on catalog.html
> +        </section>
Один section закрылся и нужно по идее открыт новый, весь контент находится в блоках, не просто так сам по себе ))

2022-01-25 16:53 UTC, hen04 commented on catalog.html
> +            <li class="view-item visually-hidden"><img src="#" alt="">Список</li>
Смотри, вот эти иконки будут переключать вид товарных карточек -- список, плитка, карточки. Наверное будет логичней сделать их кнопками

2022-01-25 16:53 UTC, hen04 commented on catalog.html
> +              <p>От 4000 ₽</p>
Заголовок тут только то, что находится в `h3`
Гостиница и цена -- отдельные элементы со своими классами

2022-01-25 16:53 UTC, hen04 commented on catalog.html
> +                </span>
Здесь не рейтинг, а количество звезд у гостиницы. 2 звезды, 3 звезды, 4 звезды, можно просто назвать `stars`

2022-01-25 16:53 UTC, hen04 commented on catalog.html
> +        <ul class="prodact-list">
опечатка )) `product`

2022-01-25 16:53 UTC, hen04 commented on catalog.html
> +          <button type="submit" value="favourites">В избранное</button>
У элементов в макете другой порядок: ![image](https://user-images.githubusercontent.com/10598166/151020730-adfad74f-cb50-43ab-9ffd-0b266a593a1c.png)

2022-01-25 16:53 UTC, hen04 commented on catalog.html
> +          <a class="pagination-link" href="">1</a>
href должен быть с решеточкой `<a class="pagination-link" href="#">1</a>`

2022-01-25 16:53 UTC, hen04 commented on catalog.html
> +      <div class="class-control">
Название класс class-control -- не совсем понятно о чем это. Можно назвать items-on-page

2022-01-25 16:53 UTC, hen04 commented on catalog.html
> +      <button class="button pagination-show-more" type="button">Загрузить ещё</button>
Это уже вторая кнопка Загрузить еще, а она одна на странице

2022-01-26 11:19 UTC, closed without merging