Разметка крупных блоков на флексах
htmlacademy-htmlcss/1932829-sedona-33 pull request #6
Opened 2022-02-10 05:59 UTC by daryadarya1

2022-02-10 15:45 UTC, hen04 requested changes
Даша, хорошо получилось, главная прям выглядит уже прилично!!
Есть мелкие правки, я кажется просмотрела ссылки в главной навигации, их нужно добавить.

2022-02-10 15:45 UTC, hen04 commented on index.html
> +          <div class="advantages-items">
А здесь `<ul>` куда-то делся. `<li>` не могут быть без родителя `<ul>`

2022-02-10 15:45 UTC, hen04 commented on styles/styles.css
> +    margin:0px;
у нулей можно не писать px, то есть `margin: 0;` лучше, чем `margin: 0px;`

2022-02-10 15:45 UTC, hen04 commented on catalog.html
>            <li class="navigation-item">Главная</li>
А где ссылки? Мне казалось, они были ))

2022-02-10 15:45 UTC, hen04 commented on index.html
>            <li class="navigation-item">О Седоне</li>
Тоже не хватает ссылок

2022-02-18 05:50 UTC, hen04 requested changes
Даша,  очень хорошо получилось сверстать микросетки. С каждой итерацией все больше и больше похоже на настоящий сайт!
Есть мелкие замечания (куда ж без них )), нужно по ним пройтись, но в целом уже прям очень хорошо. Видно, что ты много сил и внимания уделяешь деталям.

2022-02-18 05:50 UTC, hen04 commented on catalog.html
>              <fieldset class="catalog-filter-group">
`<fieldset class="catalog-filter-group">` нужно чуть-чуть сдвинуть (вложить в `<div class="catalog-filter-conteiner">`)

2022-02-18 05:50 UTC, hen04 commented on index.html
> +          <li class="navigation-item"><a href="#">Гостиницы</a></li>
В качестве улучшения можно добавить ссылки, например,  на страницу catalog.html, это страница Гостиницы

2022-02-18 05:50 UTC, hen04 commented on index.html
> +        <h2 class="tagline">Седона — небольшой городок в Аризоне, заслуживающий большего!</h2>
Кажется, класс `title` сюда подойдет лучше!

2022-02-18 05:50 UTC, hen04 commented on styles/styles.css
> +  text-decoration: none;
`text-decoration: none;` нужно прописывать непосредственно ссылке, тогда не будет подчеркивания. Сейчас прописано у блока, поэтому не применяется

2022-02-18 05:50 UTC, hen04 commented on styles/styles.css
> +}
Если смотреть через браузер, то видно, что начертание шрифта в инпуте и кнопке рядом не такое, как в макете. Инпуты и баттоны не наследуют начертания шрифта, поэтому нужно прописать еще раз тот шрифт, который есть в макете. Можно через значение свойства `inherit`

2022-02-18 05:50 UTC, hen04 commented on styles/styles.css
> +  width:200px;
Можно прописать `max-width: 180px;`, тогда "Мало туристов" будет переноситься на две строчки и будет как в макете

2022-02-18 05:50 UTC, hen04 commented on index.html
> +          <li class="navigation-item"><a href="#"><span></span><span class="visually-hidden">Отзывы</span></a></li>
В макете есть еще кружочек с количеством лайков, не забудь его сделать, пожалуйста

2022-02-18 05:50 UTC, hen04 commented on catalog.html
> +              <span class="visually-hidden"><a href="index.html">Главная</a></span>
Здесь еще должна быть иконка стрелочки, сделай ее тоже, пожалуйста, а то потом всплывет при проверке

2022-02-18 06:39 UTC, daryadarya1 commented
Спасибо, Надя!
Завтра всё исправлю и скину!
Ну, и за выходные планирую с гридами разобраться.

пт, 18 февр. 2022 г., 8:50 Надя Дегтярёва ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Даша, очень хорошо получилось сверстать микросетки. С каждой итерацией все
> больше и больше похоже на настоящий сайт!
> Есть мелкие замечания (куда ж без них )), нужно по ним пройтись, но в
> целом уже прям очень хорошо. Видно, что ты много сил и внимания уделяешь
> деталям.
> ------------------------------
>
> In catalog.html
> <https://github.com/htmlacademy-htmlcss/1932829-sedona-33/pull/6#discussion_r809684376>
> :
>
> >              </li>
>              <li class="breadcrumbs-item">
>                <a>Гостиницы</a>
>              </li>
>            </ul>
>            <h2 class="visually-hidden">Фильтр для списка гостинниц</h2>
>            <form class="catalog-filter" action="https://echo.htmlacademy.ru/" method="get">
> +            <div class="catalog-filter-conteiner">
>              <fieldset class="catalog-filter-group">
>
> <fieldset class="catalog-filter-group"> нужно чуть-чуть сдвинуть (вложить
> в <div class="catalog-filter-conteiner">)
> ------------------------------
>
> In index.html
> <https://github.com/htmlacademy-htmlcss/1932829-sedona-33/pull/6#discussion_r809686472>
> :
>
> >          <ul class="navigation-list">
> -          <li class="navigation-item">Главная</li>
> -          <li class="navigation-item">О Седоне</li>
> -          <li class="navigation-item">Гостиницы</li>
> +          <li class="navigation-item"><a href="#">Главная</a></li>
> +          <li class="navigation-item"><a href="#">О Седоне</a></li>
> +          <li class="navigation-item"><a href="#">Гостиницы</a></li>
>
> В качестве улучшения можно добавить ссылки, например, на страницу
> catalog.html, это страница Гостиницы
> ------------------------------
>
> In index.html
> <https://github.com/htmlacademy-htmlcss/1932829-sedona-33/pull/6#discussion_r809687506>
> :
>
> >        <section class="welcome-title">
>          <h1 class="visually-hidden">Welcome to Sedona</h1>
> -        <h2 class="tagline">Седона — небольшой городок в Аризоне, <br>заслуживающий большего!</h2>
> -          <p class="subtitle">Рассмотрим 5 причин, по которым Седона круче, чем Гранд-Каньон!</p>
> +        <div class="welcome-lettering"></div>
> +        <h2 class="tagline">Седона — небольшой городок в Аризоне, заслуживающий большего!</h2>
>
> Кажется, класс title сюда подойдет лучше!
> ------------------------------
>
> In styles/styles.css
> <https://github.com/htmlacademy-htmlcss/1932829-sedona-33/pull/6#discussion_r809688309>
> :
>
> > +}
> +
> +
> +.main-footer {
> +  display:flex;
> +  justify-content:space-between;
> +  min-height: 120px;
> +  width: 1200px;
> +  margin:auto;
> +}
> +
> +.footer-phone {
> +  font-size: 40px;
> +  line-height: 40px;
> +  text-transform: uppercase;
> +  text-decoration: none;
>
> text-decoration: none; нужно прописывать непосредственно ссылке, тогда не
> будет подчеркивания. Сейчас прописано у блока, поэтому не применяется
> ------------------------------
>
> In styles/styles.css
> <https://github.com/htmlacademy-htmlcss/1932829-sedona-33/pull/6#discussion_r809689229>
> :
>
> > +}
> +
> +.appointment-form{
> +  display: flex;
> +}
> +
> +input[type="email"]{
> +  margin-left:200px;
> +  padding:0px;
> +  width: 600px;
> +  height: 60px;
> +  box-sizing: border-box;
> +  border:none;
> +  border-radius: 10px 0px 0px 10px;
> +  padding: 20px;
> +}
>
> Если смотреть через браузер, то видно, что начертание шрифта в инпуте и
> кнопке рядом не такое, как в макете. Инпуты и баттоны не наследуют
> начертания шрифта, поэтому нужно прописать еще раз тот шрифт, который есть
> в макете. Можно через значение свойства inherit
> ------------------------------
>
> In styles/styles.css
> <https://github.com/htmlacademy-htmlcss/1932829-sedona-33/pull/6#discussion_r809691017>
> :
>
> > @@ -96,116 +193,179 @@ body {
>  }
>
>  .advantages-title {
> +  width:200px;
>
> Можно прописать max-width: 180px;, тогда "Мало туристов" будет
> переноситься на две строчки и будет как в макете
> ------------------------------
>
> In index.html
> <https://github.com/htmlacademy-htmlcss/1932829-sedona-33/pull/6#discussion_r809691317>
> :
>
> >          </ul>
>          <ul class="user-navigation">
> -          <li class="navigation-item"><span class="visually-hidden">Поиск</span></li>
> -          <li class="navigation-item"><span></span><span class="visually-hidden">Отзывы</span></li>
> +          <li class="navigation-item"><a href="#"><span class="visually-hidden">Поиск</span></a></li>
> +          <li class="navigation-item"><a href="#"><span></span><span class="visually-hidden">Отзывы</span></a></li>
>
> В макете есть еще кружочек с количеством лайков, не забудь его сделать,
> пожалуйста
> ------------------------------
>
> In catalog.html
> <https://github.com/htmlacademy-htmlcss/1932829-sedona-33/pull/6#discussion_r809692652>
> :
>
> > @@ -26,14 +26,15 @@
>            <h1>Гостиницы Седоны</h1>
>            <ul class="breadcrumbs-list">
>              <li class="breadcrumbs-item">
> -              <a href="index.html">Главная</a>
> +              <span class="visually-hidden"><a href="index.html">Главная</a></span>
>
> Здесь еще должна быть иконка стрелочки, сделай ее тоже, пожалуйста, а то
> потом всплывет при проверке
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/htmlacademy-htmlcss/1932829-sedona-33/pull/6#pullrequestreview-886842055>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AURSUT4UQP5NFYXGVOJCSIDU3XM3XANCNFSM5N7VFPUA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-02-19 15:02 UTC, hen04 approved these changes
Работу принимаю, но нужно учесть ряд замечаний в следующем коммите

2022-02-19 15:02 UTC, ndeg-web commented on catalog.html
> +            <a href="#about-product">О Седоне</a>
ой, тут так нельзя, нужно либо `<a href="#">`, либо `<a href="about.html">`. Но у нас такой страницы нет, так что стоит оставить первый вариант. 
Потом заметила, что ты хочешь сделать якорь, но блок только на главной, тогда ссылка на странице каталога должна быть такой: <a href="index.html#about-product">

2022-02-19 15:02 UTC, ndeg-web commented on catalog.html
> +          <div class="catalog-filter-conteiner">
опечатка в слове container

2022-02-19 15:02 UTC, ndeg-web commented on catalog.html
> +            <a>Гостиницы</a>
тут лучше подойдет `span`

2022-02-19 15:02 UTC, ndeg-web commented on catalog.html
> +            <span class="visually-hidden"><a href="index.html">Главная</a></span>
А иконка домика как раз должна быть ссылкой

2022-02-19 15:02 UTC, ndeg-web commented on catalog.html
> +        <div class="diviver"></div>
опечатка в слове divider. И наверное можно положить кнопку в див, а диву сделать полоски сверху-снизу, а внутри дива -- кнопку. Тогда не будет пустых дивов. Но это в качестве улучшения

2022-02-19 15:02 UTC, ndeg-web commented on catalog.html
> +      <section class="search-result">
кажется этот section остался не закрытым. Я посмотрела проект в своем редакторе и он подсвечивает мне ошибку.

2022-02-19 15:02 UTC, merged